spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop  #이거를 h2 console에 입력하면서 들어가면 확인가능
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
     ddl-auto: create   #실행 시점에 table을 드랍하고 다시 생성 none으로 설정하면 안그렇게 됨
    properties:
      hibernate:
     #  show_sql: true
       format_sql: true
       default_batch_fetch_size: 100    # 이거는 무조건 켜주는게 좋다. 인쿼리의 갯수 (쿼리를 많이 줄여줌 )
                                        # 1000개의 쿼리라면 10번 루프가 돈다. 1 n m 이 1 1 1 이 된다. min 100 max 1000개라고 생각
  thymeleaf:
   prefix: classpath:/templates/
   suffix: .html

logging:
  level:
    org.hibernate.SQL: debug  #logger을 통해 하버네이트 실행 sql을 남김
   # org.hibernate.type: trace #쿼리 파라메타 로그를 남겨줌
